version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ai-sales-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  livekit:
    image: livekit/livekit-server:latest
    container_name: ai-sales-livekit
    ports:
      - "7880:7880"
      - "7881:7881/udp"
    environment:
      - LIVEKIT_CONFIG=/etc/livekit.yaml
    volumes:
      - ./livekit-simple.yaml:/etc/livekit.yaml
    restart: unless-stopped

  ai-agent:
    image: livekit/agents:latest
    container_name: ai-sales-agent
    environment:
      - LIVEKIT_URL=ws://livekit:7880
      - LIVEKIT_API_KEY=your_livekit_api_key
      - LIVEKIT_API_SECRET=your_livekit_api_secret
    depends_on:
      - livekit
      - redis
    restart: unless-stopped

volumes:
  redis_data: