version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ai-sales-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  livekit:
    image: livekit/livekit-server:latest
    container_name: ai-sales-livekit
    ports:
      - "7880:7880"
      - "7881:7881/udp"
      - "5060:5060/udp"
      - "5060:5060/tcp"
    environment:
      - "LIVEKIT_KEYS=devkey: secret"
    volumes:
      - ./livekit-simple.yaml:/etc/livekit.yaml
    restart: unless-stopped

# AI agent removed - using invalid image

volumes:
  redis_data: